# YOLOv5 🚀 by Ultralytics, AGPL-3.0 license
# COCO128-seg dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017) by Ultralytics
# Example usage: python train.py --data coco128.yaml
# parent
# ├── yolov5
# └── datasets
#     └── coco128-seg  ← downloads here (7 MB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
#path: ../datasets/coco128-seg  # dataset root dir
train: C:\Users\Zycar\yolov5-master\data\cv\train  # train images (relative to 'path') 128 images
val: C:\Users\Zycar\yolov5-master\data\cv\valid  # val images (relative to 'path') 128 images
#test:  # test images (optional)

# Classes
names:
  0: aircraft carrier


# Download script/URL (optional)
download: https://ultralytics.com/assets/coco128-seg.zip
